-- Consolidated migration script
-- Generated by agent on 2026-01-07
-- Applies all individual migration steps in numeric order so a new user
-- can apply the entire schema in one run.

-- =========================================================================
-- BEGIN: 001_create_tables.sql
-- =========================================================================

-- Wedding Invitation Database Schema
-- Tables for wedding settings, guests, gallery, and comments

-- 1. Wedding Settings Table (stores all configurable wedding information)
CREATE TABLE IF NOT EXISTS wedding_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  groom_name TEXT NOT NULL DEFAULT 'Nama Mempelai Pria',
  bride_name TEXT NOT NULL DEFAULT 'Nama Mempelai Wanita',
  groom_father TEXT DEFAULT 'Nama Ayah Mempelai Pria',
  groom_mother TEXT DEFAULT 'Nama Ibu Mempelai Pria',
  bride_father TEXT DEFAULT 'Nama Ayah Mempelai Wanita',
  bride_mother TEXT DEFAULT 'Nama Ibu Mempelai Wanita',
  wedding_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  akad_time TEXT DEFAULT '08:00',
  akad_location TEXT DEFAULT 'Masjid Al-Ikhlas',
  akad_address TEXT DEFAULT 'Jl. Contoh No. 123, Jakarta',
  reception_time TEXT DEFAULT '11:00',
  reception_location TEXT DEFAULT 'Gedung Serbaguna',
  reception_address TEXT DEFAULT 'Jl. Contoh No. 456, Jakarta',
  venue_map_url TEXT DEFAULT '',
  venue_lat DECIMAL(10, 8) DEFAULT -6.2088,
  venue_lng DECIMAL(11, 8) DEFAULT 106.8456,
  love_story TEXT DEFAULT 'Cerita cinta kami dimulai...',
  quote TEXT DEFAULT 'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu isteri-isteri dari jenismu sendiri...',
  quote_source TEXT DEFAULT 'QS. Ar-Rum: 21',
  hero_image TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Guests Table (for guest management and RSVP)
CREATE TABLE IF NOT EXISTS guests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  address TEXT,
  guest_count INTEGER DEFAULT 1,
  attendance_status TEXT DEFAULT 'pending' CHECK (attendance_status IN ('pending', 'attending', 'not_attending')),
  message TEXT,
  unique_slug TEXT UNIQUE,
  is_sent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Gallery Table (for wedding photos)
CREATE TABLE IF NOT EXISTS gallery (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  image_url TEXT NOT NULL,
  caption TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Comments Table (for guest wishes/comments)
CREATE TABLE IF NOT EXISTS comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  guest_name TEXT NOT NULL,
  message TEXT NOT NULL,
  is_approved BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Admin Users Table (for dashboard access)
CREATE TABLE IF NOT EXISTS admin_users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE wedding_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- RLS Policies for wedding_settings
CREATE POLICY IF NOT EXISTS "Allow public read wedding_settings" ON wedding_settings FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Allow admin update wedding_settings" ON wedding_settings FOR UPDATE USING (auth.uid() IN (SELECT id FROM admin_users));
CREATE POLICY IF NOT EXISTS "Allow admin insert wedding_settings" ON wedding_settings FOR INSERT WITH CHECK (auth.uid() IN (SELECT id FROM admin_users));

-- RLS Policies for guests
CREATE POLICY IF NOT EXISTS "Allow public read guests by slug" ON guests FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Allow public update guest RSVP" ON guests FOR UPDATE USING (true);
CREATE POLICY IF NOT EXISTS "Allow admin all guests" ON guests FOR ALL USING (auth.uid() IN (SELECT id FROM admin_users));

-- RLS Policies for gallery
CREATE POLICY IF NOT EXISTS "Allow public read gallery" ON gallery FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Allow admin all gallery" ON gallery FOR ALL USING (auth.uid() IN (SELECT id FROM admin_users));

-- RLS Policies for comments
CREATE POLICY IF NOT EXISTS "Allow public read approved comments" ON comments FOR SELECT USING (is_approved = true);
CREATE POLICY IF NOT EXISTS "Allow public insert comments" ON comments FOR INSERT WITH CHECK (true);
CREATE POLICY IF NOT EXISTS "Allow admin all comments" ON comments FOR ALL USING (auth.uid() IN (SELECT id FROM admin_users));

-- RLS Policies for admin_users
CREATE POLICY IF NOT EXISTS "Allow admin read admin_users" ON admin_users FOR SELECT USING (auth.uid() = id);
CREATE POLICY IF NOT EXISTS "Allow admin insert admin_users" ON admin_users FOR INSERT WITH CHECK (auth.uid() = id);

-- Create trigger for auto-create admin on signup
CREATE OR REPLACE FUNCTION public.handle_new_admin()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.admin_users (id, email, name)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data ->> 'name', new.email)
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_admin();

-- Insert default wedding settings
INSERT INTO wedding_settings (id) VALUES (gen_random_uuid()) ON CONFLICT DO NOTHING;

-- Realtime comment publication (best effort)
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE comments;
  EXCEPTION WHEN undefined_table THEN
    -- Publication or supabase_realtime may not exist in all environments; ignore
    RAISE NOTICE 'supabase_realtime publication absent, skipping';
  END;
END;
$$;


-- =========================================================================
-- BEGIN: 002_drop_guest_email.sql
-- =========================================================================

-- Migration: Drop email column from guests table
ALTER TABLE IF EXISTS guests
  DROP COLUMN IF EXISTS email;


-- =========================================================================
-- BEGIN: 003_add_whatsapp_template.sql
-- =========================================================================

ALTER TABLE IF EXISTS wedding_settings
  ADD COLUMN IF NOT EXISTS whatsapp_template text;


-- =========================================================================
-- BEGIN: 004_refactor_guests.sql
-- =========================================================================

ALTER TABLE IF EXISTS guests
  ADD COLUMN IF NOT EXISTS unique_code text;

ALTER TABLE IF EXISTS guests
  ADD COLUMN IF NOT EXISTS invited_at timestamptz;

ALTER TABLE IF EXISTS guests
  ADD COLUMN IF NOT EXISTS last_blasted_at timestamptz;

ALTER TABLE IF EXISTS guests
  ADD COLUMN IF NOT EXISTS blast_status text;

ALTER TABLE IF EXISTS guests
  ADD COLUMN IF NOT EXISTS opt_out boolean DEFAULT false;

ALTER TABLE IF EXISTS guests
  ADD COLUMN IF NOT EXISTS phone_normalized text;

CREATE INDEX IF NOT EXISTS idx_guests_phone_normalized ON guests (phone_normalized);

-- Backfill simple unique_code for existing rows that lack it
UPDATE guests
SET unique_code = substring(md5(random()::text || clock_timestamp()::text), 1, 10)
WHERE unique_code IS NULL;


-- =========================================================================
-- BEGIN: 005_add_slug_backfill.sql
-- =========================================================================

ALTER TABLE IF EXISTS guests
  ADD COLUMN IF NOT EXISTS slug text;

UPDATE guests
SET slug = lower(regexp_replace(coalesce(name, ''), '[^a-z0-9]+', '-', 'g')) || '-' ||
           coalesce(substring(unique_code, 1, 6), substring(md5(id::text), 1, 6))
WHERE slug IS NULL OR slug = '';


-- =========================================================================
-- BEGIN: 006_add_site_meta.sql
-- =========================================================================

ALTER TABLE IF EXISTS wedding_settings
  ADD COLUMN IF NOT EXISTS site_name text;

ALTER TABLE IF EXISTS wedding_settings
  ADD COLUMN IF NOT EXISTS favicon text;


-- =========================================================================
-- BEGIN: 007_add_couple_photos.sql
-- =========================================================================

ALTER TABLE IF EXISTS wedding_settings
  ADD COLUMN IF NOT EXISTS groom_photo text,
  ADD COLUMN IF NOT EXISTS bride_photo text;


-- =========================================================================
-- BEGIN: 008_add_background_image.sql
-- =========================================================================

-- NOTE: this migration file was intentionally marked removed in the repo.
-- If background_image is required, run the following manually:
-- ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS background_image text;


-- =========================================================================
-- BEGIN: 009_add_splash_columns.sql
-- =========================================================================

BEGIN;

ALTER TABLE wedding_settings
  ADD COLUMN IF NOT EXISTS splash_image text;

ALTER TABLE wedding_settings
  ADD COLUMN IF NOT EXISTS splash_overlay_opacity numeric DEFAULT 0.8;

ALTER TABLE wedding_settings
  ADD COLUMN IF NOT EXISTS splash_overlay_mode text DEFAULT 'light';

ALTER TABLE wedding_settings
  ADD COLUMN IF NOT EXISTS splash_overlay_color text;

UPDATE wedding_settings
  SET splash_overlay_opacity = 0.8
  WHERE splash_overlay_opacity IS NULL;

UPDATE wedding_settings
  SET splash_overlay_mode = 'light'
  WHERE splash_overlay_mode IS NULL;

COMMIT;


-- =========================================================================
-- BEGIN: 010_add_event_end_times.sql
-- =========================================================================

ALTER TABLE wedding_settings
ADD COLUMN IF NOT EXISTS akad_time_end TEXT,
ADD COLUMN IF NOT EXISTS reception_time_end TEXT;

UPDATE wedding_settings
SET akad_time_end = 'Selesai',
    reception_time_end = 'Selesai'
WHERE akad_time_end IS NULL OR reception_time_end IS NULL;


-- =========================================================================
-- BEGIN: 011_clear_gallery.sql
-- =========================================================================

DELETE FROM gallery;


-- =========================================================================
-- BEGIN: 012_add_countdown_target_date.sql
-- =========================================================================

ALTER TABLE wedding_settings
ADD COLUMN countdown_target_date TIMESTAMPTZ;


-- =========================================================================
-- BEGIN: 013_add_section_customization.sql
-- =========================================================================

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS section_title_bismillah TEXT DEFAULT 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS section_title_couple TEXT DEFAULT 'The Happy Couple';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS section_title_countdown TEXT DEFAULT 'Save The Date';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS section_title_event TEXT DEFAULT 'Wedding Event';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS section_title_gallery TEXT DEFAULT 'Our Gallery';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS section_title_rsvp TEXT DEFAULT 'RSVP';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS section_title_comments TEXT DEFAULT 'Wishes & Prayers';

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS countdown_bg_image TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS event_bg_image TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS gallery_bg_image TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS rsvp_bg_image TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS comments_bg_image TEXT;

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS countdown_bg_overlay INTEGER DEFAULT 80;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS event_bg_overlay INTEGER DEFAULT 80;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS gallery_bg_overlay INTEGER DEFAULT 80;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS rsvp_bg_overlay INTEGER DEFAULT 80;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS comments_bg_overlay INTEGER DEFAULT 80;

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS closing_message TEXT DEFAULT 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu kepada kami. Terima kasih.';

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS footer_copyright TEXT DEFAULT '© 2025 Wedding Invitation';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS footer_social_instagram TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS footer_social_facebook TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS footer_social_twitter TEXT;


-- =========================================================================
-- BEGIN: 014_add_background_styling_options.sql
-- =========================================================================

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS background_opacity INTEGER DEFAULT 100;

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS countdown_bg_mode TEXT DEFAULT 'image';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS countdown_bg_color TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS countdown_bg_blur INTEGER DEFAULT 0;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS countdown_overlay_color TEXT;

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS event_bg_mode TEXT DEFAULT 'image';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS event_bg_color TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS event_bg_blur INTEGER DEFAULT 0;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS event_overlay_color TEXT;

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS gallery_bg_mode TEXT DEFAULT 'image';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS gallery_bg_color TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS gallery_bg_blur INTEGER DEFAULT 0;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS gallery_overlay_color TEXT;

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS rsvp_bg_mode TEXT DEFAULT 'image';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS rsvp_bg_color TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS rsvp_bg_blur INTEGER DEFAULT 0;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS rsvp_overlay_color TEXT;

ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS comments_bg_mode TEXT DEFAULT 'image';
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS comments_bg_color TEXT;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS comments_bg_blur INTEGER DEFAULT 0;
ALTER TABLE wedding_settings ADD COLUMN IF NOT EXISTS comments_overlay_color TEXT;


-- =========================================================================
-- BEGIN: 015_add_og_image.sql
-- =========================================================================

ALTER TABLE wedding_settings 
ADD COLUMN IF NOT EXISTS og_image TEXT;

COMMENT ON COLUMN wedding_settings.og_image IS 'Custom Open Graph preview image for social media sharing (1200x630px recommended)';


-- =========================================================================
-- BEGIN: 016_add_hint_box_text.sql
-- =========================================================================

ALTER TABLE wedding_settings 
ADD COLUMN IF NOT EXISTS hint_box_text TEXT;

COMMENT ON COLUMN wedding_settings.hint_box_text IS 'Custom text for the floating hint box (gift notice)';

UPDATE wedding_settings 
SET hint_box_text = 'Dengan segala kerendahan hati, kami tidak menerima kado saat acara. Terimakasih ❤️'
WHERE hint_box_text IS NULL;


-- =========================================================================
-- BEGIN: 017_add_og_description.sql
-- =========================================================================

ALTER TABLE wedding_settings
  ADD COLUMN IF NOT EXISTS og_description TEXT;

COMMENT ON COLUMN wedding_settings.og_description IS 'Custom description used for link previews and meta description for social sharing (WhatsApp/Facebook/Twitter)';


-- =========================================================================
-- BEGIN: 018_add_og_version.sql
-- =========================================================================

ALTER TABLE wedding_settings 
ADD COLUMN IF NOT EXISTS og_version INTEGER DEFAULT 1 NOT NULL;

COMMENT ON COLUMN wedding_settings.og_version IS 'Version number for OG image cache busting. Increment to force social platforms to refetch preview.';

UPDATE wedding_settings SET og_version = 1 WHERE og_version IS NULL;

-- End of consolidated migration
